"use client";

import Cookies from "js-cookie";
import { useRouter } from "next/navigation";
import { useEffect } from "react";

export default function Home() {
  const router = useRouter();

  useEffect(() => {
    const role = Cookies.get("role");
    if (role === "TEACHER") {
      router.push("/teacher");
    } else if (role === "STUDENT") {
      router.push("/student");
    }
  }, [router]);

  const login = (role) => {
    Cookies.set("role", role);
    router.push(role === "TEACHER" ? "/teacher" : "/student");
    // Force a small reload for the navbar to pick it up if needed
    window.location.href = role === "TEACHER" ? "/teacher" : "/student";
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", minHeight: "70vh", textAlign: "center" }}>
      <h1 className="h1" style={{ marginBottom: "1rem", color: "var(--foreground)" }}>Welcome to Exam Buddy</h1>
      <p className="p" style={{ maxWidth: "600px", marginBottom: "3rem" }}>
        The ultimate educational resource hub. Access previous year question papers, notes, and expected questions generated by AI.
      </p>

      <div style={{ display: "flex", gap: "2rem", flexWrap: "wrap", justifyContent: "center" }}>
        <div className="card" style={{ width: "300px", display: "flex", flexDirection: "column", alignItems: "center", gap: "1.5rem" }}>
          <div style={{ fontSize: "3rem" }}>👨‍🏫</div>
          <h2 className="h2">Teacher</h2>
          <p className="p" style={{ fontSize: "0.95rem" }}>Upload study materials, manage PDFs, and help students prepare.</p>
          <button className="btn" style={{ width: "100%" }} onClick={() => login("TEACHER")}>
            Login as Teacher
          </button>
        </div>

        <div className="card" style={{ width: "300px", display: "flex", flexDirection: "column", alignItems: "center", gap: "1.5rem" }}>
          <div style={{ fontSize: "3rem" }}>👨‍🎓</div>
          <h2 className="h2">Student</h2>
          <p className="p" style={{ fontSize: "0.95rem" }}>Access notes, papers, and use AI to generate expected questions.</p>
          <button className="btn" style={{ width: "100%" }} onClick={() => login("STUDENT")}>
            Login as Student
          </button>
        </div>
      </div>
    </div>
  );
}
